//! Build script: the embedded marketplace table, the target triple and the
//! git revision.
//!
//! Three things the compiler cannot work out on its own end up here.
//!
//! 1. `$OUT_DIR/embedded_files.rs` is the `(path, contents)` table
//!    `src/registry/embedded.rs` includes. It is generated from
//!    `vendor/marketplace/registry.yaml` and the model files that index lists,
//!    so `scripts/vendor-marketplace.sh` is the only step needed when upstream
//!    adds or drops a model: there is no hand-written list to forget.
//! 2. `TARGET` is the triple this binary is being built for, which
//!    `chaps self update` needs to pick its release asset.
//! 3. `GIT_REVISION` is the short commit of the checkout, empty when there is
//!    no git or no repository, which `chaps self version` reports.

use std::path::{Path, PathBuf};

/// The vendored snapshot, relative to the crate root.
const VENDOR_DIR: &str = "vendor/marketplace";
/// The index inside it, which names every model file to embed.
const INDEX_FILE: &str = "registry.yaml";

fn main() {
    let root = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));

    emit_target();
    emit_git_revision(&root);
    emit_embedded_files(&root, &out_dir);
}

/// The triple being built for, so the running binary can name its own release
/// asset without guessing from `cfg!` flags.
fn emit_target() {
    let target = std::env::var("TARGET").unwrap_or_else(|_| "unknown".to_string());
    println!("cargo:rustc-env=TARGET={target}");
}

/// The short commit of this checkout, or an empty string.
///
/// A release build from a tarball, a vendored crate or a machine without git
/// all land in the empty case, which is not an error: the revision is extra
/// detail on top of the version, never something the CLI depends on.
fn emit_git_revision(root: &Path) {
    // Emitting any rerun-if-changed key turns off cargo's "rerun when any
    // file changed" default, so the two files that decide the revision are
    // named explicitly. A detached HEAD has no ref file, hence the `if let`.
    let git_dir = root.join(".git");
    if git_dir.join("HEAD").is_file() {
        println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
        if let Ok(head) = std::fs::read_to_string(git_dir.join("HEAD"))
            && let Some(reference) = head.trim().strip_prefix("ref: ")
        {
            let path = git_dir.join(reference);
            if path.is_file() {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }

    let revision = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(root)
        .output()
        .ok()
        .filter(|out| out.status.success())
        .and_then(|out| String::from_utf8(out.stdout).ok())
        .map(|text| text.trim().to_string())
        .unwrap_or_default();
    println!("cargo:rustc-env=GIT_REVISION={revision}");
}

/// Write the `(relative path, contents)` table for the vendored snapshot.
///
/// `registry.yaml` is always first and the model files follow in index order,
/// which is the order the rest of the crate expects.
fn emit_embedded_files(root: &Path, out_dir: &Path) {
    let vendor = root.join(VENDOR_DIR);
    let index_path = vendor.join(INDEX_FILE);

    println!("cargo:rerun-if-changed={}", index_path.display());
    println!("cargo:rerun-if-changed={}", vendor.join("models").display());
    println!("cargo:rerun-if-changed={}", vendor.display());

    let index = std::fs::read_to_string(&index_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", index_path.display()));

    let mut entries: Vec<String> = vec![INDEX_FILE.to_string()];
    entries.extend(model_paths(&index));

    for rel in &entries[1..] {
        let path = vendor.join(rel);
        assert!(
            path.is_file(),
            "{} lists {rel}, which is not in {}; run scripts/vendor-marketplace.sh",
            index_path.display(),
            vendor.display()
        );
    }
    warn_about_unlisted(&vendor, &entries);

    let mut generated = String::from(
        "// @generated by build.rs from vendor/marketplace; do not edit.\n\
         const FILES: &[(&str, &str)] = &[\n",
    );
    for rel in &entries {
        let path = vendor.join(rel);
        generated.push_str(&format!(
            "    ({}, include_str!({})),\n",
            literal(rel),
            literal(&display_path(&path))
        ));
    }
    generated.push_str("];\n");

    let dest = out_dir.join("embedded_files.rs");
    std::fs::write(&dest, generated).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}

/// The `- models/<id>.yaml` entries under the index's `models:` key.
///
/// Parsed by hand rather than with a YAML crate so the build script pulls in
/// no dependencies of its own; the file is generated by
/// `scripts/vendor-marketplace.sh`, which reads it with the same one-entry-
/// per-line shape.
fn model_paths(index: &str) -> Vec<String> {
    let mut paths = Vec::new();
    for line in index.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix('-') else {
            continue;
        };
        let value = rest.trim().trim_matches(['"', '\'']);
        if value.starts_with("models/") && (value.ends_with(".yaml") || value.ends_with(".yml")) {
            paths.push(value.to_string());
        }
    }
    assert!(
        !paths.is_empty(),
        "no `- models/<id>.yaml` entries in {VENDOR_DIR}/{INDEX_FILE}"
    );
    paths
}

/// Say something about a model file that is on disk but not in the index.
///
/// A warning rather than an error: an unlisted file is dead weight, not a
/// broken build, and `scripts/vendor-marketplace.sh` deletes them anyway.
fn warn_about_unlisted(vendor: &Path, entries: &[String]) {
    let Ok(dir) = std::fs::read_dir(vendor.join("models")) else {
        return;
    };
    let mut extra: Vec<String> = dir
        .flatten()
        .filter_map(|entry| entry.file_name().into_string().ok())
        .filter(|name| name.ends_with(".yaml") || name.ends_with(".yml"))
        .map(|name| format!("models/{name}"))
        .filter(|rel| !entries.iter().any(|listed| listed == rel))
        .collect();
    extra.sort();
    for rel in extra {
        println!(
            "cargo:warning={VENDOR_DIR}/{rel} is not listed in {INDEX_FILE} and is not embedded"
        );
    }
}

/// A path as a string `include_str!` accepts on every platform.
///
/// Windows paths are written with forward slashes, which rustc accepts and
/// which keeps the generated file free of escape sequences.
fn display_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}

/// `text` as a Rust string literal.
fn literal(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}
