//! Filling the compose text templates.
//!
//! The templates are plain text with `@KEY@` tokens rather than a template
//! engine, because compose's own `${VAR:-default}` syntax collides with the
//! usual `{{ }}` delimiters and a serde round trip would drop the comments.
//!
//! Owned by agent B.

use crate::compose::overrides;
use crate::compose::spec::{BaseSpec, EnvSpec, OverlaySpec};

/// chap-core's `compose.ghcr.yml`, verbatim but for the header comment.
const BASE_TEMPLATE: &str = include_str!("templates/compose.base.yml");

/// Second line of every generated `compose.yml`, whichever copy of
/// `compose.ghcr.yml` the body came from. The first line says where that was.
const BASE_OVERLAY_NOTE: &str =
    "# Model services live in compose.<service>.yml overlays included by compose.marketplace.yml.";

/// One model service, as a compose overlay.
const OVERLAY_TEMPLATE: &str = include_str!("templates/compose.overlay.yml");
/// The generated `.env`.
const ENV_TEMPLATE: &str = include_str!("templates/env.example");

/// Placeholder for the pin section of a `.env` with no models enabled, so the
/// section never renders as a dangling heading above a blank line.
pub(crate) const NO_TAG_PINS: &str = "# (none yet; `chaps models enable` adds one line per model)";

/// Render the base `compose.yml`.
///
/// With `spec.upstream` the body is chap-core's own `compose.ghcr.yml` at that
/// tag, byte for byte, behind the same two-line header the vendored copy
/// carries; without it the copy compiled into the binary is filled in. Both
/// renderings are a pure function of the project state, which is what lets
/// `chaps sync` treat `compose.yml` as an artifact.
pub fn render_base(spec: &BaseSpec) -> String {
    let Some(upstream) = &spec.upstream else {
        return fill(BASE_TEMPLATE, &[("CLI_VERSION", &spec.cli_version)]);
    };
    let mut out = format!(
        "# Generated by chaps init ({}) from chap-core compose.ghcr.yml at {}.\n\
         {BASE_OVERLAY_NOTE}\n",
        spec.cli_version, upstream.tag
    );
    out.push_str(&upstream.body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Render the generated `.env`.
pub fn render_env(spec: &EnvSpec) -> String {
    // An active line only when the tag says something `latest` does not.
    let chap_image_tag_line = match spec.chap_image_tag.as_deref() {
        Some(tag) if tag != "latest" => format!("CHAP_IMAGE_TAG={tag}"),
        _ => "# CHAP_IMAGE_TAG=latest".to_string(),
    };
    let pins = if spec.model_tag_pins.is_empty() {
        NO_TAG_PINS.to_string()
    } else {
        spec.model_tag_pins
            .iter()
            .map(|(var, tag)| format!("# {var}={tag}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    fill(
        ENV_TEMPLATE,
        &[
            ("CLI_VERSION", &spec.cli_version),
            ("POSTGRES_USER", &spec.postgres_user),
            ("POSTGRES_PASSWORD", &spec.postgres_password),
            ("POSTGRES_DB", &spec.postgres_db),
            ("CHAP_IMAGE_TAG_LINE", &chap_image_tag_line),
            ("MODEL_TAG_PINS", &pins),
        ],
    )
}

/// Render one `compose.<service_id>.yml` overlay.
pub fn render_overlay(spec: &OverlaySpec) -> String {
    // The token sits at the start of its line and carries its own newline, so
    // an image that needs no platform pin leaves no blank line behind.
    let platform_line = match spec.platform.as_deref() {
        Some(p) => format!("    platform: {p}\n"),
        None => String::new(),
    };
    // chap-core only checks the key when it is configured, so the default is
    // the commented pair from chap-core's own compose.ewars.yml.
    let registration_key_lines = if spec.registration_key {
        "      SERVICEKIT_REGISTRATION_KEY: ${SERVICEKIT_REGISTRATION_KEY:-}".to_string()
    } else {
        concat!(
            "      # Uncomment if chap has SERVICEKIT_REGISTRATION_KEY set:\n",
            "      # SERVICEKIT_REGISTRATION_KEY: ${SERVICEKIT_REGISTRATION_KEY:-}"
        )
        .to_string()
    };
    let host_port = spec.host_port.to_string();
    // The init container chowns the data volume from busybox, which knows none
    // of the images' account names; an unresolvable one falls back to the
    // chapkit ids (`chaps sync` warns about it).
    let uid_gid = overrides::numeric_user(&spec.user)
        .unwrap_or_else(|| overrides::FALLBACK_UID_GID.to_string());
    fill(
        OVERLAY_TEMPLATE,
        &[
            ("CLI_VERSION", &spec.cli_version),
            ("SERVICE_ID", &spec.service_id),
            ("DISPLAY_NAME", &spec.display_name),
            ("ID", &spec.id),
            ("VERSION", &spec.version),
            ("REPOSITORY", &spec.repository),
            ("TAG_VAR", &spec.tag_env_var),
            ("IMAGE_TAG", &spec.image_tag),
            ("IMAGE", &spec.image),
            ("PLATFORM_LINE", &platform_line),
            ("HOST_PORT", &host_port),
            ("REGISTRATION_KEY_LINES", &registration_key_lines),
            ("DATA_DIR", &spec.data_dir),
            ("USER", &spec.user),
            ("UID_GID", &uid_gid),
            ("VOLUME", &spec.volume_name),
        ],
    )
}

/// Render `compose.marketplace.yml` from the ordered overlay file names.
///
/// With no overlays this must emit `services: {}` rather than an empty
/// `include:` list, which compose rejects.
pub fn render_umbrella(files: &[String]) -> String {
    let mut out = String::new();
    out.push_str(
        "# compose.marketplace.yml - generated by chaps; rendered from .chaps/models.yaml by `chaps sync`.\n\
         # It includes one overlay per enabled model service.\n\
         # Requires Docker Compose v2.20+ for the `include` directive.\n",
    );
    if files.is_empty() {
        out.push_str(
            "# No models are enabled; `chaps models enable ID` adds an include line here.\n\
             services: {}\n",
        );
        return out;
    }
    out.push_str("\ninclude:\n");
    for file in files {
        out.push_str(&format!("  - {file}\n"));
    }
    out
}

/// Replace every `@KEY@` token in `template` with its value.
pub(crate) fn fill(template: &str, vars: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (key, value) in vars {
        out = out.replace(&format!("@{key}@"), value);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compose::spec::UpstreamCompose;
    use crate::compose::{tag_env_var, volume_name};
    use crate::registry::{Channel, VersionSelector, load_embedded};
    use serde_yaml_ng::Value;

    /// Nothing may leave an `@KEY@` behind; `@` on its own is legal YAML (the
    /// base file has one in a postgres URL), so only the token shape counts.
    fn assert_no_tokens(text: &str) {
        let re = regex::Regex::new(r"@[A-Z][A-Z0-9_]*@").unwrap();
        assert!(
            !re.is_match(text),
            "unfilled token: {:?}",
            re.find(text).map(|m| m.as_str())
        );
    }

    fn overlay_spec(id: &str, host_port: u16) -> OverlaySpec {
        let registry = load_embedded().unwrap();
        let m = registry.get(id).unwrap();
        let v = m
            .resolve(&VersionSelector::Channel(Channel::Stable))
            .unwrap();
        OverlaySpec::from_model(m, v, host_port, None, None, "0.1.0")
    }

    fn parse(text: &str) -> Value {
        serde_yaml_ng::from_str(text).expect("generated compose parses as YAML")
    }

    fn service<'a>(doc: &'a Value, name: &str) -> &'a Value {
        &doc["services"][name]
    }

    #[test]
    fn fill_replaces_every_token() {
        let out = fill("a=@A@ b=@B@ a=@A@", &[("A", "1"), ("B", "2")]);
        assert_eq!(out, "a=1 b=2 a=1");
    }

    #[test]
    fn fill_leaves_compose_variables_alone() {
        let out = fill("${TAG:-sha-1234567} @TAG@", &[("TAG", "x")]);
        assert_eq!(out, "${TAG:-sha-1234567} x");
    }

    #[test]
    fn overlay_matches_the_golden_fixture() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model", 5002));
        let golden = include_str!("../../tests/fixtures/compose.chapkit-ewars-model.yml");
        assert_eq!(text, golden);
    }

    #[test]
    fn overlay_keeps_the_chap_core_deployment_invariants() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model", 5002));
        assert_no_tokens(&text);
        // `$$register` must survive verbatim: `$register` would expand away.
        assert!(text.contains("http://chap:8000/v2/services/$$register"));

        let doc = parse(&text);
        let svc = service(&doc, "chapkit-ewars-model");
        assert_eq!(svc["restart"].as_str(), Some("unless-stopped"));
        assert_eq!(svc["init"].as_bool(), Some(true));
        assert_eq!(svc["read_only"].as_bool(), Some(true));
        assert_eq!(svc["user"].as_str(), Some("chapkit:chapkit"));

        // chap-core/tests/test_compose_deployment.py: a pinned sha build behind
        // an overridable ${<ID>_IMAGE_TAG:-sha-xxxxxxx}, and no pull_policy.
        let image = svc["image"].as_str().unwrap();
        let re = regex::Regex::new(
            r"^ghcr\.io/[a-z0-9._/-]+:\$\{[A-Z0-9_]+_IMAGE_TAG:-sha-[0-9a-f]{7}\}$",
        )
        .unwrap();
        assert!(re.is_match(image), "unexpected image {image:?}");
        assert!(
            svc.get("pull_policy").is_none(),
            "pull_policy defeats the pin"
        );

        // No networks: the default network reaches chap but not redis/postgres.
        assert!(svc.get("networks").is_none());
        // chapkit images ship their own HEALTHCHECK.
        assert!(svc.get("healthcheck").is_none());

        assert_eq!(
            svc["ports"],
            Value::Sequence(vec![Value::String("5002:8000".into())])
        );
        assert_eq!(
            svc["depends_on"]["chap"]["condition"].as_str(),
            Some("service_healthy")
        );

        // The named volume is declared as well as mounted.
        let volume = volume_name("chapkit_ewars_model");
        assert_eq!(svc["volumes"][1]["source"].as_str(), Some(volume.as_str()));
        assert_eq!(svc["volumes"][1]["target"].as_str(), Some("/app/data"));
        assert!(doc["volumes"].get(volume.as_str()).is_some());

        // Two services, and only the model carries the restart policy: the
        // init container is a one-shot by design.
        let services = doc["services"].as_mapping().unwrap();
        assert_eq!(services.len(), 2);
    }

    #[test]
    fn overlay_hands_the_data_volume_to_the_model_user_before_it_starts() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model", 5002));
        let doc = parse(&text);
        let init = service(&doc, "chapkit-ewars-model-init");

        // Docker seeds a fresh named volume from the image, ownership
        // included, and root-owns it when the image has no such directory;
        // the model would then fail to open its SQLite file.
        assert_eq!(init["image"].as_str(), Some("busybox:1.37"));
        assert_eq!(init["user"].as_str(), Some("0:0"));
        // Numeric: busybox knows no `chapkit` account.
        assert_eq!(
            init["command"],
            Value::Sequence(vec![
                "sh".into(),
                "-c".into(),
                "chown 1000:1000 /app/data".into()
            ])
        );
        assert!(!text.contains("chown chapkit"));
        // Quoted, or YAML would read it as the boolean false.
        assert!(text.contains("    restart: \"no\"\n"));
        assert_eq!(init["restart"].as_str(), Some("no"));
        // Multi-arch, so no platform pin is needed.
        assert!(init.get("platform").is_none());
        assert!(init.get("ports").is_none());

        // Same volume at the same path as the model service.
        let volume = volume_name("chapkit_ewars_model");
        assert_eq!(init["volumes"][0]["source"].as_str(), Some(volume.as_str()));
        assert_eq!(init["volumes"][0]["target"].as_str(), Some("/app/data"));

        // And the model waits for it to finish.
        let svc = service(&doc, "chapkit-ewars-model");
        assert_eq!(
            svc["depends_on"]["chapkit-ewars-model-init"]["condition"].as_str(),
            Some("service_completed_successfully")
        );
    }

    #[test]
    fn overlay_chowns_to_the_ids_of_the_user_the_model_runs_as() {
        // The simple multistep image runs as `chap`, which is uid/gid 1001.
        let text = render_overlay(&overlay_spec("chapkit_simple_multistep_model", 5003));
        assert!(text.contains("chown 1001:1001 /app/data"), "{text}");

        // A numeric --user is passed through, and the data dir follows it.
        let mut spec = overlay_spec("auto_arima_chapkit", 5004);
        spec.user = "1500:1600".into();
        spec.data_dir = "/srv/data".into();
        assert!(render_overlay(&spec).contains("chown 1500:1600 /srv/data"));

        // An account no image of ours creates falls back to the chapkit ids
        // rather than rendering a chown busybox would reject.
        spec.user = "nobody".into();
        let text = render_overlay(&spec);
        assert!(text.contains("chown 1000:1000 /srv/data"), "{text}");
        assert_eq!(
            service(&parse(&text), "auto-arima-chapkit")["user"].as_str(),
            Some("nobody")
        );
    }

    #[test]
    fn overlay_pins_the_platform_and_drops_the_line_cleanly_without_one() {
        let inla = render_overlay(&overlay_spec("chapkit_ewars_model", 5002));
        let doc = parse(&inla);
        assert_eq!(
            service(&doc, "chapkit-ewars-model")["platform"].as_str(),
            Some("linux/amd64")
        );

        let mut spec = overlay_spec("chapkit_simple_multistep_model", 5003);
        spec.platform = None;
        let portable = render_overlay(&spec);
        let doc = parse(&portable);
        let svc = service(&doc, "chapkit-simple-multistep-model");
        assert!(svc.get("platform").is_none(), "no platform when unset");
        // Dropping the platform line must not leave a blank line behind.
        assert!(
            portable.contains("    image: ghcr.io/chap-models/chapkit_simple_multistep_model:")
        );
        assert!(!portable.contains("\n\n    init: true"));
        assert!(portable.contains("\n    init: true\n"));
        assert_no_tokens(&portable);
    }

    #[test]
    fn overlay_registration_key_is_commented_until_asked_for() {
        let mut spec = overlay_spec("auto_arima_chapkit", 5004);
        let commented = render_overlay(&spec);
        assert!(
            commented.contains("      # Uncomment if chap has SERVICEKIT_REGISTRATION_KEY set:")
        );
        let doc = parse(&commented);
        assert!(
            service(&doc, "auto-arima-chapkit")["environment"]
                .get("SERVICEKIT_REGISTRATION_KEY")
                .is_none()
        );

        spec.registration_key = true;
        let active = render_overlay(&spec);
        assert!(!active.contains("# Uncomment"));
        let doc = parse(&active);
        assert_eq!(
            service(&doc, "auto-arima-chapkit")["environment"]["SERVICEKIT_REGISTRATION_KEY"]
                .as_str(),
            // Left for compose to expand, not resolved at generation time.
            Some("${SERVICEKIT_REGISTRATION_KEY:-}")
        );
    }

    #[test]
    fn overlay_header_names_the_model_and_its_tag_variable() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model", 5002));
        let header: Vec<&str> = text.lines().take(4).collect();
        assert!(
            header[0].starts_with("# compose.chapkit-ewars-model.yml - generated by chaps (0.1.0)")
        );
        assert!(header[1].contains("CHAP-EWARS (chapkit_ewars_model) v1.0.0"));
        assert!(header[1].contains("https://github.com/chap-models/chapkit_ewars_model"));
        assert!(header[3].contains(&tag_env_var("chapkit_ewars_model")));
    }

    #[test]
    fn base_needs_no_env_file_and_keeps_the_networks_split() {
        let text = render_base(&BaseSpec {
            cli_version: "0.1.0".into(),
            upstream: None,
        });
        assert_no_tokens(&text);
        assert!(
            text.starts_with("# Generated by chaps init (0.1.0) from chap-core compose.ghcr.yml.")
        );
        assert!(text.contains("compose.marketplace.yml"));
        assert!(!text.contains("An alternative to compose.yml"));

        // chap-core's test_standalone_compose_needs_no_env_file.
        let bare = regex::Regex::new(r"\$\{[A-Z_]+\}").unwrap();
        assert!(
            !bare.is_match(&text),
            "variable without default: {:?}",
            bare.find(&text).map(|m| m.as_str())
        );

        let doc = parse(&text);
        for name in ["chap", "worker"] {
            let svc = service(&doc, name);
            assert_eq!(
                svc["networks"],
                Value::Sequence(vec!["default".into(), "backend".into()]),
                "{name} must join both networks"
            );
            let image = svc["image"].as_str().unwrap();
            assert!(
                image.ends_with(":${CHAP_IMAGE_TAG:-latest}"),
                "{name} pins {image:?}"
            );
        }
        for name in ["redis", "postgres"] {
            assert_eq!(
                service(&doc, name)["networks"],
                Value::Sequence(vec!["backend".into()]),
                "{name} must stay off the default network"
            );
        }
        let services = doc["services"].as_mapping().unwrap();
        assert_eq!(services.len(), 4);
        for (name, svc) in services {
            assert_eq!(
                svc["restart"].as_str(),
                Some("unless-stopped"),
                "{name:?} has no restart policy"
            );
        }
        assert!(doc["networks"].get("backend").is_some());
    }

    #[test]
    fn base_from_upstream_keeps_the_fetched_body_verbatim() {
        // Only the first line differs between the two renderings; the second
        // is the same note, and everything after it is upstream's.
        let body = "services:\n  chap:\n    image: ghcr.io/x:${CHAP_IMAGE_TAG:-latest}\n";
        let text = render_base(&BaseSpec {
            cli_version: "0.1.0".into(),
            upstream: Some(UpstreamCompose {
                tag: "v2.3.1".into(),
                body: body.to_string(),
            }),
        });
        assert_no_tokens(&text);
        assert_eq!(
            text,
            format!(
                "# Generated by chaps init (0.1.0) from chap-core compose.ghcr.yml at v2.3.1.\n\
                 {BASE_OVERLAY_NOTE}\n{body}"
            )
        );
        assert!(text.ends_with('\n'));
        assert_eq!(
            service(&parse(&text), "chap")["image"].as_str(),
            Some("ghcr.io/x:${CHAP_IMAGE_TAG:-latest}")
        );

        // A body without a trailing newline still ends the file cleanly.
        let text = render_base(&BaseSpec {
            cli_version: "0.1.0".into(),
            upstream: Some(UpstreamCompose {
                tag: "master".into(),
                body: "services: {}".into(),
            }),
        });
        assert!(text.ends_with("services: {}\n"));
        assert!(text.starts_with(
            "# Generated by chaps init (0.1.0) from chap-core compose.ghcr.yml at master.\n"
        ));
    }

    /// The header of the vendored copy is what the fetched rendering imitates;
    /// if one moves, the other has to move with it.
    #[test]
    fn both_base_renderings_share_their_second_header_line() {
        assert_eq!(BASE_TEMPLATE.lines().nth(1), Some(BASE_OVERLAY_NOTE));
    }

    #[test]
    fn umbrella_with_no_models_is_an_empty_service_map() {
        let text = render_umbrella(&[]);
        let doc = parse(&text);
        assert!(doc.get("include").is_none(), "an empty include is rejected");
        assert_eq!(
            doc["services"],
            Value::Mapping(serde_yaml_ng::Mapping::new())
        );
    }

    #[test]
    fn umbrella_includes_one_line_per_overlay() {
        let one = render_umbrella(&["compose.chapkit-ewars-model.yml".to_string()]);
        let doc = parse(&one);
        assert_eq!(
            doc["include"],
            Value::Sequence(vec!["compose.chapkit-ewars-model.yml".into()])
        );
        assert!(doc.get("services").is_none());

        let files: Vec<String> = ["a", "b", "c"]
            .iter()
            .map(|n| format!("compose.{n}.yml"))
            .collect();
        let three = render_umbrella(&files);
        let doc = parse(&three);
        assert_eq!(
            doc["include"],
            Value::Sequence(files.iter().map(|f| f.as_str().into()).collect())
        );
        assert!(three.contains("Compose v2.20+"));
    }

    fn env_spec() -> EnvSpec {
        EnvSpec {
            postgres_user: "chap".into(),
            postgres_password: "0123456789abcdef0123456789abcdef".into(),
            postgres_db: "chap_core".into(),
            chap_image_tag: None,
            model_tag_pins: Vec::new(),
            cli_version: "0.1.0".into(),
        }
    }

    #[test]
    fn env_writes_the_postgres_credentials() {
        let text = render_env(&env_spec());
        assert_no_tokens(&text);
        assert!(text.contains("\nPOSTGRES_USER=chap\n"));
        assert!(text.contains("\nPOSTGRES_PASSWORD=0123456789abcdef0123456789abcdef\n"));
        assert!(text.contains("\nPOSTGRES_DB=chap_core\n"));
        assert!(text.contains("\n# CHAP_API_TOKEN=\n"));
        assert!(text.contains("openssl rand -hex 32"));
        assert!(text.contains("\n# SERVICEKIT_REGISTRATION_KEY=\n"));
        assert!(text.contains("\n# CHAP_DATABASE_URL=\n"));
        assert!(text.ends_with('\n'));
    }

    #[test]
    fn env_activates_the_chap_tag_only_when_it_is_pinned() {
        for tag in [None, Some("latest".to_string())] {
            let text = render_env(&EnvSpec {
                chap_image_tag: tag.clone(),
                ..env_spec()
            });
            assert!(text.contains("\n# CHAP_IMAGE_TAG=latest\n"), "{tag:?}");
        }
        let text = render_env(&EnvSpec {
            chap_image_tag: Some("v1.2.3".into()),
            ..env_spec()
        });
        assert!(text.contains("\nCHAP_IMAGE_TAG=v1.2.3\n"));
        assert!(!text.contains("# CHAP_IMAGE_TAG"));
    }

    #[test]
    fn env_lists_one_commented_pin_per_model() {
        let text = render_env(&EnvSpec {
            model_tag_pins: vec![
                (tag_env_var("chapkit_ewars_model"), "sha-fa880a1".into()),
                (tag_env_var("auto_arima_chapkit"), "sha-70c07a9".into()),
            ],
            ..env_spec()
        });
        assert!(text.contains("\n# CHAPKIT_EWARS_MODEL_IMAGE_TAG=sha-fa880a1\n"));
        assert!(text.contains("\n# AUTO_ARIMA_CHAPKIT_IMAGE_TAG=sha-70c07a9\n"));
        assert!(!text.contains("none yet"));

        // Without models the section keeps a body rather than a blank line.
        let empty = render_env(&env_spec());
        assert!(empty.contains(NO_TAG_PINS));
        assert!(!empty.ends_with("\n\n"));
    }
}
