//! Filling the compose text templates.
//!
//! The templates are plain text with `@KEY@` tokens rather than a template
//! engine, because compose's own `${VAR:-default}` syntax collides with the
//! usual `{{ }}` delimiters and a serde round trip would drop the comments.
//!
//! Owned by agent B.

use crate::auth::{API_TOKEN_ENV_VAR, REGISTRATION_KEY_ENV_VAR};
use crate::components::{
    OCS_CONFIG_FILE, OCS_CONTAINER_PORT, OCS_DIR, OCS_IMAGE, OCS_TAG_ENV_VAR,
    S3_ACCESS_KEY_ENV_VAR, S3_BUCKET, S3_CONTAINER_PORT, S3_IMAGE, S3_SECRET_KEY_ENV_VAR,
    S3_TAG_ENV_VAR,
};
use crate::compose::overrides;
use crate::compose::spec::{BaseSpec, EnvSpec, OcsConfigSpec, OcsSpec, OverlaySpec, S3Spec};
use crate::project::API_PORT_ENV_VAR;
use std::sync::LazyLock;

/// Rewrite CRLF line endings as LF.
///
/// Every file rendered here is compared byte for byte: by `chaps sync`
/// against what is on disk, and by the tests against the golden fixture. The
/// templates are compiled in with `include_str!`, so on a Windows checkout
/// with git's default `core.autocrlf` they would arrive with CRLF and the
/// rendered file would differ from the same file rendered anywhere else.
/// Passing them through here once makes the output `\n` on every platform,
/// whatever the checkout did.
pub(crate) fn normalize_newlines(text: &str) -> String {
    text.replace("\r\n", "\n")
}

/// chap-core's `compose.ghcr.yml`, verbatim but for the header comment.
static BASE_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/compose.base.yml")));

/// The first line of every compose file `chaps sync` renders, templates
/// included.
///
/// It says what the file is and where to change it, and nothing else: the
/// explanations live in the docs, so an upgrade of this CLI never rewrites a
/// paragraph in someone's deployment.
pub(crate) const GENERATED_HEADER: &str =
    "# Generated by chaps from .chaps/; edit there and run `chaps sync`.";

/// One model service, as a compose overlay.
static OVERLAY_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/compose.overlay.yml")));
/// The generated `.env`.
static ENV_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/env.example")));
/// The `ocs` component, as a compose file of its own.
static OCS_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/compose.ocs.yml")));
/// The `s3` component, likewise.
static S3_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/compose.s3.yml")));
/// The OCS instance config `init --with ocs` scaffolds.
static OCS_CONFIG_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/climate-service.yaml")));

/// Named volume holding OCS's data directory.
pub const OCS_VOLUME: &str = "ocs_data";
/// Named volume holding the object store's data directory.
pub const S3_VOLUME: &str = "s3_data";
/// Region the bucket request is signed for. RustFS ignores it, but SigV4 has
/// to name one.
const S3_REGION: &str = "us-east-1";

/// The marker line the scaffolded `ocs/climate-service.yaml` carries while it
/// still holds OCS's example values.
///
/// `chaps doctor` looks for exactly this, and the note tells the reader to
/// delete it once the file is theirs, so the check goes quiet by itself.
pub const OCS_EXAMPLE_MARKER: &str = "# These are OCS's own Sierra Leone example values.";

/// Placeholder for the pin section of a `.env` with no models enabled, so the
/// section never renders as a dangling heading above a blank line.
pub(crate) const NO_TAG_PINS: &str = "# (none yet; `chaps models enable` adds one line per model)";

/// Render the base `compose.yml`.
///
/// With `spec.upstream` the body is chap-core's own `compose.ghcr.yml` at that
/// tag, byte for byte but for its line endings, behind the shared header line
/// plus one naming the tag; without it the copy compiled into the binary is
/// used as it is. Both renderings are a pure function of the project state,
/// which is what lets `chaps sync` treat `compose.yml` as an artifact.
pub fn render_base(spec: &BaseSpec) -> String {
    let Some(upstream) = &spec.upstream else {
        return BASE_TEMPLATE.clone();
    };
    let mut out = format!(
        "{GENERATED_HEADER}\n# chap-core compose.ghcr.yml at {}\n",
        upstream.tag
    );
    out.push_str(&normalize_newlines(&upstream.body));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Render `compose.chaps.yml`: the chaps-owned settings that sit on top of
/// the fetched `compose.yml`.
///
/// It exists because the base file is upstream's, byte for byte, and because
/// `include:` cannot override a service the main file defines - only a
/// separate `-f` entry can. The `!override` tag (Compose 2.24.4+, which is why
/// that is this CLI's supported minimum) replaces chap's own `ports:` list
/// rather than adding to it, which is what keeps the API on exactly one host
/// port.
///
/// `api_port` is rendered as the `${CHAP_API_PORT:-...}` default, so the file
/// stands on its own while `.env` stays the way to change the port without
/// touching `.chaps/`.
///
/// `project_name` is the top-level `name:`, which is what keeps this
/// deployment's containers and volumes to itself; see [`project_name_block`].
///
/// The `environment:` block hands chap-core the registration key. Upstream's
/// `compose.ghcr.yml` passes only `CHAP_API_TOKEN` into the service, so a
/// deployment with authentication on has a chap-core that knows the API token
/// and not the key - and then rejects every model's `X-Service-Key` with a
/// 401. Compose merges `environment` maps across `-f` files additively, so
/// this adds the one variable without touching upstream's file. It is
/// rendered whether or not the deployment has a key: with none in `.env` the
/// variable arrives empty, which is what chap-core reads as "not set".
pub fn render_chaps_overlay(api_port: u16, project_name: Option<&str>) -> String {
    format!(
        "{GENERATED_HEADER}\n\
         {}\
         services:\n\
         \x20 chap:\n\
         \x20   ports: !override\n\
         \x20     - \"${{{API_PORT_ENV_VAR}:-{api_port}}}:8000\"\n\
         \x20   environment:\n\
         \x20     {REGISTRATION_KEY_ENV_VAR}: ${{{REGISTRATION_KEY_ENV_VAR}:-}}\n",
        project_name_block(project_name)
    )
}

/// The top-level `name:` key.
///
/// Without it compose names the project after the directory, so two
/// deployments in directories of the same name share every container name and
/// every named volume - a fresh `chaps up` then inherits the database of a
/// deployment it has never heard of. Compose takes the `name:` of the last
/// `-f` file that sets one, so every chaps-owned file carries the same value
/// and any subset of the `-f` list names the same project.
///
/// Empty for a deployment whose directory name compose can make no project
/// name out of at all; compose falls back to its own rule there, as it always
/// has.
pub(crate) fn project_name_block(project_name: Option<&str>) -> String {
    match project_name {
        Some(name) => format!("name: {name}\n"),
        None => String::new(),
    }
}

/// Render the generated `.env`.
pub fn render_env(spec: &EnvSpec) -> String {
    // An active line only when the tag says something `latest` does not.
    let chap_image_tag_line = match spec.chap_image_tag.as_deref() {
        Some(tag) if tag != "latest" => format!("CHAP_IMAGE_TAG={tag}"),
        _ => "# CHAP_IMAGE_TAG=latest".to_string(),
    };
    let pins = if spec.model_tag_pins.is_empty() {
        NO_TAG_PINS.to_string()
    } else {
        spec.model_tag_pins
            .iter()
            .map(|(var, tag)| format!("# {var}={tag}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    fill(
        &ENV_TEMPLATE,
        &[
            ("POSTGRES_USER", &spec.postgres_user),
            ("POSTGRES_PASSWORD", &spec.postgres_password),
            ("POSTGRES_DB", &spec.postgres_db),
            ("CHAP_IMAGE_TAG_LINE", &chap_image_tag_line),
            ("API_PORT", &spec.api_port.to_string()),
            (
                "CHAP_API_TOKEN_LINE",
                &secret_line(API_TOKEN_ENV_VAR, spec.api_token.as_deref()),
            ),
            (
                "REGISTRATION_KEY_LINE",
                &secret_line(REGISTRATION_KEY_ENV_VAR, spec.registration_key.as_deref()),
            ),
            ("MODEL_TAG_PINS", &pins),
        ],
    )
}

/// One secret's `.env` line: an active assignment when there is a value, and
/// otherwise the commented placeholder.
///
/// The placeholder is written even when the deployment has no authentication,
/// so the variable is discoverable where an operator would look for it, and so
/// `chaps auth enable` has a line to uncomment in place rather than appending
/// one at the bottom of the file.
fn secret_line(var: &str, value: Option<&str>) -> String {
    match value {
        Some(value) => format!("{var}={value}"),
        None => format!("# {var}="),
    }
}

/// Render `compose.ocs.yml`: the `ocs` component.
///
/// The `S3_*` block only appears when the `s3` component is on. OCS does not
/// read those variables yet - it is about to - so they are written as
/// forward-looking settings with a comment that says as much, rather than
/// being left out until the day the contract lands.
pub fn render_ocs(spec: &OcsSpec) -> String {
    let s3_lines = if spec.s3 {
        format!(
            "      # Forward-looking: OCS does not read these yet.\n\
             \x20     S3_ENDPOINT: http://s3:{S3_CONTAINER_PORT}\n\
             \x20     {S3_ACCESS_KEY_ENV_VAR}: ${{{S3_ACCESS_KEY_ENV_VAR}:-}}\n\
             \x20     {S3_SECRET_KEY_ENV_VAR}: ${{{S3_SECRET_KEY_ENV_VAR}:-}}\n\
             \x20     S3_BUCKET: {S3_BUCKET}\n"
        )
    } else {
        String::new()
    };
    fill(
        &OCS_TEMPLATE,
        &[
            ("IMAGE", OCS_IMAGE),
            ("TAG_VAR", OCS_TAG_ENV_VAR),
            ("IMAGE_TAG", &spec.image_tag),
            ("HOST_PORT", &spec.host_port.to_string()),
            ("CONTAINER_PORT", &OCS_CONTAINER_PORT.to_string()),
            ("S3_LINES", &s3_lines),
            ("CONFIG_PATH", &format!("{OCS_DIR}/{OCS_CONFIG_FILE}")),
            ("VOLUME", OCS_VOLUME),
        ],
    )
}

/// Render `compose.s3.yml`: the `s3` component.
pub fn render_s3(spec: &S3Spec) -> String {
    let port_lines = match spec.host_port {
        None => format!("    expose:\n      - \"{S3_CONTAINER_PORT}\"\n"),
        Some(port) => format!(
            "    expose:\n      - \"{S3_CONTAINER_PORT}\"\n\
             \x20   ports:\n      - \"{port}:{S3_CONTAINER_PORT}\"\n"
        ),
    };
    fill(
        &S3_TEMPLATE,
        &[
            ("IMAGE", S3_IMAGE),
            ("TAG_VAR", S3_TAG_ENV_VAR),
            ("IMAGE_TAG", &spec.image_tag),
            ("PORT_LINES", &port_lines),
            ("CONTAINER_PORT", &S3_CONTAINER_PORT.to_string()),
            ("ACCESS_KEY_VAR", S3_ACCESS_KEY_ENV_VAR),
            ("SECRET_KEY_VAR", S3_SECRET_KEY_ENV_VAR),
            ("BUCKET", S3_BUCKET),
            ("REGION", S3_REGION),
            ("VOLUME", S3_VOLUME),
        ],
    )
}

/// Render the scaffolded `ocs/climate-service.yaml`.
///
/// Written once, when the component is enabled, and never again: it is the
/// operator's file from that moment on.
pub fn render_ocs_config(spec: &OcsConfigSpec) -> String {
    // The token starts its own line and carries its own newlines, so a file
    // written from real values leaves no blank comment block behind.
    let note = if spec.example {
        format!("{OCS_EXAMPLE_MARKER} Edit them, then delete this note.\n")
    } else {
        String::new()
    };
    fill(
        &OCS_CONFIG_TEMPLATE,
        &[
            ("EXAMPLE_NOTE", &note),
            ("ID", &spec.id),
            ("NAME", &spec.name),
            ("EXTENT_NAME", &spec.extent_name),
            ("BBOX", &spec.bbox),
            ("COUNTRY_CODE", &spec.country_code),
        ],
    )
}

/// Render one `compose.<service_id>.yml` overlay.
pub fn render_overlay(spec: &OverlaySpec) -> String {
    // The token sits at the start of its line and carries its own newline, so
    // an image that needs no platform pin leaves neither a comment nor a blank
    // line behind.
    let platform_line = match spec.platform.as_deref() {
        Some(p) => format!(
            "    # amd64-only image; the pin makes an arm64 host pull that variant.\n\
             \x20   platform: {p}\n"
        ),
        None => String::new(),
    };
    // chap-core only checks the key when it is configured, so the default is
    // the commented pair from chap-core's own compose.ewars.yml. With
    // authentication on, the value is left for compose to substitute: it reads
    // the `.env` next to these files, so the key never has to be copied into
    // `.chaps/` or into an overlay.
    let registration_key_lines = if spec.registration_key {
        "      SERVICEKIT_REGISTRATION_KEY: ${SERVICEKIT_REGISTRATION_KEY:-}".to_string()
    } else {
        concat!(
            "      # Uncomment if chap has SERVICEKIT_REGISTRATION_KEY set:\n",
            "      # SERVICEKIT_REGISTRATION_KEY: ${SERVICEKIT_REGISTRATION_KEY:-}"
        )
        .to_string()
    };
    let port_lines = port_lines(spec);
    // The init container chowns the data volume from busybox, which knows none
    // of the images' account names; an unresolvable one falls back to the
    // chapkit ids (`chaps sync` warns about it).
    let uid_gid = overrides::numeric_user(&spec.user)
        .unwrap_or_else(|| overrides::FALLBACK_UID_GID.to_string());
    fill(
        &OVERLAY_TEMPLATE,
        &[
            ("SERVICE_ID", &spec.service_id),
            ("ID", &spec.id),
            ("VERSION", &spec.version),
            ("REPOSITORY", &spec.repository),
            ("TAG_VAR", &spec.tag_env_var),
            ("IMAGE_TAG", &spec.image_tag),
            ("IMAGE", &spec.image),
            // A digest carries its own `@`, so the reference is joined with
            // nothing rather than with a colon.
            ("TAG_SEP", crate::compose::tag_separator(&spec.image_tag)),
            ("PLATFORM_LINE", &platform_line),
            ("PORT_LINES", &port_lines),
            ("REGISTRATION_KEY_LINES", &registration_key_lines),
            ("DATA_DIR", &spec.data_dir),
            ("USER", &spec.user),
            ("UID_GID", &uid_gid),
            ("VOLUME", &spec.volume_name),
        ],
    )
}

/// The `expose:` (and, when one was asked for, `ports:`) block of one model
/// overlay, indented for the service and ending in its own newline.
///
/// A model needs no host port to work: chap-core reaches it at
/// `http://<service_id>:8000` on the compose default network, which is the URL
/// the service registers, and a human reaches it through chap-core's read-only
/// proxy. `expose` documents the container port without asking the host for
/// anything. A published port is for people - `curl`, the model's own `/docs` -
/// and is opt-in per model. See `docs/ports.md`.
fn port_lines(spec: &OverlaySpec) -> String {
    let mut out = String::from("    expose:\n      - \"8000\"\n");
    if let Some(port) = spec.host_port {
        out.push_str(&format!("    ports:\n      - \"{port}:8000\"\n"));
    }
    out
}

/// Render `compose.marketplace.yml` from the ordered overlay file names.
///
/// With no overlays this must emit `services: {}` rather than an empty
/// `include:` list, which compose rejects.
///
/// It carries the project `name:` as well, and it is the one file that is
/// always in the `-f` list: a deployment with `chap-core` turned off has no
/// `compose.chaps.yml` to carry it.
pub fn render_umbrella(files: &[String], project_name: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(&project_name_block(project_name));
    if files.is_empty() {
        out.push_str("services: {}\n");
        return out;
    }
    out.push_str("include:\n");
    for file in files {
        out.push_str(&format!("  - {file}\n"));
    }
    out
}

/// Replace every `@KEY@` token in `template` with its value.
pub(crate) fn fill(template: &str, vars: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (key, value) in vars {
        out = out.replace(&format!("@{key}@"), value);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compose::spec::{OcsConfigSpec, UpstreamCompose};
    use crate::compose::{tag_env_var, volume_name};
    use crate::registry::{Channel, VersionSelector, load_embedded};
    use serde_yaml_ng::Value;

    /// Nothing may leave an `@KEY@` behind; `@` on its own is legal YAML (the
    /// base file has one in a postgres URL), so only the token shape counts.
    fn assert_no_tokens(text: &str) {
        let re = regex::Regex::new(r"@[A-Z][A-Z0-9_]*@").unwrap();
        assert!(
            !re.is_match(text),
            "unfilled token: {:?}",
            re.find(text).map(|m| m.as_str())
        );
    }

    /// A spec for a model that publishes no host port: the default.
    fn overlay_spec(id: &str) -> OverlaySpec {
        let registry = load_embedded().unwrap();
        let m = registry.get(id).unwrap();
        let v = m
            .resolve(&VersionSelector::Channel(Channel::Stable))
            .unwrap();
        OverlaySpec::from_model(m, v, None, None, None)
    }

    /// The same, published on `host_port`.
    fn published_spec(id: &str, host_port: u16) -> OverlaySpec {
        OverlaySpec {
            host_port: Some(host_port),
            ..overlay_spec(id)
        }
    }

    fn parse(text: &str) -> Value {
        serde_yaml_ng::from_str(text).expect("generated compose parses as YAML")
    }

    fn service<'a>(doc: &'a Value, name: &str) -> &'a Value {
        &doc["services"][name]
    }

    #[test]
    fn fill_replaces_every_token() {
        let out = fill("a=@A@ b=@B@ a=@A@", &[("A", "1"), ("B", "2")]);
        assert_eq!(out, "a=1 b=2 a=1");
    }

    #[test]
    fn fill_leaves_compose_variables_alone() {
        let out = fill("${TAG:-sha-1234567} @TAG@", &[("TAG", "x")]);
        assert_eq!(out, "${TAG:-sha-1234567} x");
    }

    #[test]
    fn overlay_matches_the_golden_fixture() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model"));
        let golden = normalize_newlines(include_str!(
            "../../tests/fixtures/compose.chapkit-ewars-model.yml"
        ));
        assert_eq!(text, golden);
    }

    #[test]
    fn an_overlay_publishes_a_port_only_when_one_was_asked_for() {
        // The default: exposed on the compose network, invisible to the host.
        let internal = render_overlay(&overlay_spec("chapkit_ewars_model"));
        assert_no_tokens(&internal);
        assert!(internal.contains("\n    expose:\n      - \"8000\"\n"));
        assert!(!internal.contains("    ports:"));
        // Dropping the ports block must not leave a blank line behind.
        assert!(internal.contains("\n    environment:\n"));
        assert!(!internal.contains("\n\n    environment:"));

        // With a port, both keys: `expose` still documents the container port,
        // and `ports` is the mapping Docker publishes.
        let published = render_overlay(&published_spec("chapkit_ewars_model", 5002));
        assert_no_tokens(&published);
        let svc = &parse(&published)["services"]["chapkit-ewars-model"];
        assert_eq!(
            svc["expose"],
            Value::Sequence(vec![Value::String("8000".into())])
        );
        assert_eq!(
            svc["ports"],
            Value::Sequence(vec![Value::String("5002:8000".into())])
        );
    }

    #[test]
    fn the_chaps_overlay_replaces_the_api_port_rather_than_adding_to_it() {
        let text = render_chaps_overlay(8000, None);
        assert_no_tokens(&text);
        assert!(text.starts_with(&format!("{GENERATED_HEADER}\n")));
        // `!override` is what makes this a replacement: a plain `ports:` list
        // would merge with the one compose.yml already has.
        assert!(text.contains("    ports: !override\n      - \"${CHAP_API_PORT:-8000}:8000\"\n"));
        assert!(text.ends_with('\n'));

        // The recorded port is the variable's default, so the file works
        // without .env and moves when `.chaps/project.yaml` does.
        assert!(render_chaps_overlay(8123, None).contains("${CHAP_API_PORT:-8123}:8000"));

        // It parses, tag and all, and names one service.
        let doc = parse(&text);
        let services = doc["services"].as_mapping().unwrap();
        assert_eq!(services.len(), 1);
        assert!(services.contains_key("chap"));
    }

    #[test]
    fn the_chaps_overlay_names_the_compose_project() {
        let text = render_chaps_overlay(8000, Some("mychap-1ab2c3"));
        assert_no_tokens(&text);
        assert!(text.contains("\nname: mychap-1ab2c3\n"), "{text}");
        assert_eq!(
            parse(&text)["name"].as_str(),
            Some("mychap-1ab2c3"),
            "compose reads it as the project name"
        );
        // Without a name the key is absent rather than empty: compose would
        // reject `name:` with nothing after it.
        assert!(!render_chaps_overlay(8000, None).contains("name:"));
    }

    #[test]
    fn the_chaps_overlay_hands_chap_core_the_registration_key() {
        // Upstream's compose.ghcr.yml passes only CHAP_API_TOKEN into the
        // container, so without this line a protected chap-core has no key to
        // check a model's X-Service-Key against and answers 401.
        let text = render_chaps_overlay(8000, Some("mychap-1ab2c3"));
        let env = &parse(&text)["services"]["chap"]["environment"];
        assert_eq!(
            env["SERVICEKIT_REGISTRATION_KEY"].as_str(),
            Some("${SERVICEKIT_REGISTRATION_KEY:-}")
        );
        // Rendered whether or not the deployment has a key: compose
        // substitutes an empty value, which chap-core reads as no key.
        assert!(render_chaps_overlay(8000, None).contains("SERVICEKIT_REGISTRATION_KEY:"));
    }

    #[test]
    fn overlay_keeps_the_chap_core_deployment_invariants() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model"));
        assert_no_tokens(&text);
        // `$$register` must survive verbatim: `$register` would expand away.
        assert!(text.contains("http://chap:8000/v2/services/$$register"));

        let doc = parse(&text);
        let svc = service(&doc, "chapkit-ewars-model");
        assert_eq!(svc["restart"].as_str(), Some("unless-stopped"));
        assert_eq!(svc["init"].as_bool(), Some(true));
        assert_eq!(svc["read_only"].as_bool(), Some(true));
        assert_eq!(svc["user"].as_str(), Some("chapkit:chapkit"));

        // chap-core/tests/test_compose_deployment.py: a pinned sha build behind
        // an overridable ${<ID>_IMAGE_TAG:-sha-xxxxxxx}, and no pull_policy.
        let image = svc["image"].as_str().unwrap();
        let re = regex::Regex::new(
            r"^ghcr\.io/[a-z0-9._/-]+:\$\{[A-Z0-9_]+_IMAGE_TAG:-sha-[0-9a-f]{7}\}$",
        )
        .unwrap();
        assert!(re.is_match(image), "unexpected image {image:?}");
        assert!(
            svc.get("pull_policy").is_none(),
            "pull_policy defeats the pin"
        );

        // No networks: the default network reaches chap but not redis/postgres.
        assert!(svc.get("networks").is_none());
        // chapkit images ship their own HEALTHCHECK.
        assert!(svc.get("healthcheck").is_none());
        // Both facts live in docs/models.md, not in a comment in every file.
        assert!(!text.contains("# No `networks:`"));
        assert!(!text.contains("# No healthcheck"));

        // No host port by default: only the container port is declared.
        assert_eq!(
            svc["expose"],
            Value::Sequence(vec![Value::String("8000".into())])
        );
        assert!(svc.get("ports").is_none(), "a model publishes nothing");
        assert_eq!(
            svc["depends_on"]["chap"]["condition"].as_str(),
            Some("service_healthy")
        );

        // The named volume is declared as well as mounted.
        let volume = volume_name("chapkit_ewars_model");
        assert_eq!(svc["volumes"][1]["source"].as_str(), Some(volume.as_str()));
        assert_eq!(svc["volumes"][1]["target"].as_str(), Some("/app/data"));
        assert!(doc["volumes"].get(volume.as_str()).is_some());

        // Two services, and only the model carries the restart policy: the
        // init container is a one-shot by design.
        let services = doc["services"].as_mapping().unwrap();
        assert_eq!(services.len(), 2);
    }

    #[test]
    fn overlay_hands_the_data_volume_to_the_model_user_before_it_starts() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model"));
        let doc = parse(&text);
        let init = service(&doc, "chapkit-ewars-model-init");

        // Docker seeds a fresh named volume from the image, ownership
        // included, and root-owns it when the image has no such directory;
        // the model would then fail to open its SQLite file.
        assert_eq!(init["image"].as_str(), Some("busybox:1.37"));
        assert_eq!(init["user"].as_str(), Some("0:0"));
        // Numeric: busybox knows no `chapkit` account.
        assert_eq!(
            init["command"],
            Value::Sequence(vec![
                "sh".into(),
                "-c".into(),
                "chown 1000:1000 /app/data".into()
            ])
        );
        assert!(!text.contains("chown chapkit"));
        // Quoted, or YAML would read it as the boolean false.
        assert!(text.contains("    restart: \"no\"\n"));
        assert_eq!(init["restart"].as_str(), Some("no"));
        // Multi-arch, so no platform pin is needed.
        assert!(init.get("platform").is_none());
        assert!(init.get("ports").is_none());

        // Same volume at the same path as the model service.
        let volume = volume_name("chapkit_ewars_model");
        assert_eq!(init["volumes"][0]["source"].as_str(), Some(volume.as_str()));
        assert_eq!(init["volumes"][0]["target"].as_str(), Some("/app/data"));

        // And the model waits for it to finish.
        let svc = service(&doc, "chapkit-ewars-model");
        assert_eq!(
            svc["depends_on"]["chapkit-ewars-model-init"]["condition"].as_str(),
            Some("service_completed_successfully")
        );
    }

    #[test]
    fn overlay_chowns_to_the_ids_of_the_user_the_model_runs_as() {
        // The simple multistep image runs as `chap`, which is uid/gid 1001.
        let text = render_overlay(&overlay_spec("chapkit_simple_multistep_model"));
        assert!(text.contains("chown 1001:1001 /app/data"), "{text}");

        // A numeric --user is passed through, and the data dir follows it.
        let mut spec = overlay_spec("auto_arima_chapkit");
        spec.user = "1500:1600".into();
        spec.data_dir = "/srv/data".into();
        assert!(render_overlay(&spec).contains("chown 1500:1600 /srv/data"));

        // An account no image of ours creates falls back to the chapkit ids
        // rather than rendering a chown busybox would reject.
        spec.user = "nobody".into();
        let text = render_overlay(&spec);
        assert!(text.contains("chown 1000:1000 /srv/data"), "{text}");
        assert_eq!(
            service(&parse(&text), "auto-arima-chapkit")["user"].as_str(),
            Some("nobody")
        );
    }

    #[test]
    fn an_overlay_pinned_to_a_digest_renders_a_digest_reference() {
        let mut spec = overlay_spec("auto_arima_chapkit");
        let digest = format!("@sha256:{}", "b".repeat(64));
        spec.image_tag = digest.clone();
        spec.version = digest.clone();
        let text = render_overlay(&spec);
        assert_no_tokens(&text);
        assert!(
            text.contains(&format!(
                "    image: ghcr.io/chap-models/auto_arima_chapkit${{AUTO_ARIMA_CHAPKIT_IMAGE_TAG:-{digest}}}\n"
            )),
            "{text}"
        );
        // Compose reads it as one reference, digest and all.
        let image = parse(&text)["services"]["auto-arima-chapkit"]["image"]
            .as_str()
            .unwrap()
            .to_string();
        assert!(image.contains(":-@sha256:"), "{image}");
    }

    #[test]
    fn overlay_pins_the_platform_and_drops_the_line_cleanly_without_one() {
        let inla = render_overlay(&overlay_spec("chapkit_ewars_model"));
        let doc = parse(&inla);
        assert_eq!(
            service(&doc, "chapkit-ewars-model")["platform"].as_str(),
            Some("linux/amd64")
        );

        // One short line says why the pin is there, and it goes with the pin.
        assert!(inla.contains("    # amd64-only image;"), "{inla}");

        let mut spec = overlay_spec("chapkit_simple_multistep_model");
        spec.platform = None;
        let portable = render_overlay(&spec);
        let doc = parse(&portable);
        let svc = service(&doc, "chapkit-simple-multistep-model");
        assert!(svc.get("platform").is_none(), "no platform when unset");
        // Dropping the platform line takes its comment with it, and leaves no
        // blank line behind.
        assert!(
            portable.contains("    image: ghcr.io/chap-models/chapkit_simple_multistep_model:")
        );
        assert!(!portable.contains("amd64-only"));
        assert!(!portable.contains("\n\n    init: true"));
        assert!(portable.contains("\n    init: true\n"));
        assert_no_tokens(&portable);
    }

    #[test]
    fn overlay_registration_key_is_commented_until_asked_for() {
        let mut spec = overlay_spec("auto_arima_chapkit");
        let commented = render_overlay(&spec);
        assert!(
            commented.contains("      # Uncomment if chap has SERVICEKIT_REGISTRATION_KEY set:")
        );
        let doc = parse(&commented);
        assert!(
            service(&doc, "auto-arima-chapkit")["environment"]
                .get("SERVICEKIT_REGISTRATION_KEY")
                .is_none()
        );

        spec.registration_key = true;
        let active = render_overlay(&spec);
        assert_no_tokens(&active);
        assert!(!active.contains("# Uncomment"));
        let doc = parse(&active);
        assert_eq!(
            service(&doc, "auto-arima-chapkit")["environment"]["SERVICEKIT_REGISTRATION_KEY"]
                .as_str(),
            // Left for compose to expand, not resolved at generation time.
            Some("${SERVICEKIT_REGISTRATION_KEY:-}")
        );
    }

    /// Two lines and no more: the shared one, then the model this file is.
    #[test]
    fn overlay_header_is_the_shared_line_plus_the_model() {
        let text = render_overlay(&overlay_spec("chapkit_ewars_model"));
        let header: Vec<&str> = text.lines().take(3).collect();
        assert_eq!(header[0], GENERATED_HEADER);
        assert_eq!(
            header[1],
            "# chapkit_ewars_model 1.0.0 (https://github.com/chap-models/chapkit_ewars_model)"
        );
        assert_eq!(header[2], "services:", "no third comment line");
        // The tag variable is in the image line, which is the only place it
        // does anything.
        assert!(text.contains(&format!(
            "${{{}:-sha-fa880a1}}",
            tag_env_var("chapkit_ewars_model")
        )));
    }

    #[test]
    fn base_needs_no_env_file_and_keeps_the_networks_split() {
        let text = render_base(&BaseSpec { upstream: None });
        assert_no_tokens(&text);
        assert_eq!(text.lines().next(), Some(GENERATED_HEADER));
        assert_eq!(text.lines().nth(1), Some("services:"), "one header line");

        // chap-core's test_standalone_compose_needs_no_env_file.
        let bare = regex::Regex::new(r"\$\{[A-Z_]+\}").unwrap();
        assert!(
            !bare.is_match(&text),
            "variable without default: {:?}",
            bare.find(&text).map(|m| m.as_str())
        );

        let doc = parse(&text);
        for name in ["chap", "worker"] {
            let svc = service(&doc, name);
            assert_eq!(
                svc["networks"],
                Value::Sequence(vec!["default".into(), "backend".into()]),
                "{name} must join both networks"
            );
            let image = svc["image"].as_str().unwrap();
            assert!(
                image.ends_with(":${CHAP_IMAGE_TAG:-latest}"),
                "{name} pins {image:?}"
            );
        }
        for name in ["redis", "postgres"] {
            assert_eq!(
                service(&doc, name)["networks"],
                Value::Sequence(vec!["backend".into()]),
                "{name} must stay off the default network"
            );
        }
        let services = doc["services"].as_mapping().unwrap();
        assert_eq!(services.len(), 4);
        for (name, svc) in services {
            assert_eq!(
                svc["restart"].as_str(),
                Some("unless-stopped"),
                "{name:?} has no restart policy"
            );
        }
        assert!(doc["networks"].get("backend").is_some());
    }

    #[test]
    fn base_from_upstream_keeps_the_fetched_body_verbatim() {
        // Only the first line differs between the two renderings; the second
        // is the same note, and everything after it is upstream's.
        let body = "services:\n  chap:\n    image: ghcr.io/x:${CHAP_IMAGE_TAG:-latest}\n";
        let text = render_base(&BaseSpec {
            upstream: Some(UpstreamCompose {
                tag: "v2.3.1".into(),
                body: body.to_string(),
            }),
        });
        assert_no_tokens(&text);
        assert_eq!(
            text,
            format!("{GENERATED_HEADER}\n# chap-core compose.ghcr.yml at v2.3.1\n{body}")
        );
        assert!(text.ends_with('\n'));
        assert_eq!(
            service(&parse(&text), "chap")["image"].as_str(),
            Some("ghcr.io/x:${CHAP_IMAGE_TAG:-latest}")
        );

        // A body without a trailing newline still ends the file cleanly.
        let text = render_base(&BaseSpec {
            upstream: Some(UpstreamCompose {
                tag: "master".into(),
                body: "services: {}".into(),
            }),
        });
        assert!(text.ends_with("services: {}\n"));
        assert!(text.contains("# chap-core compose.ghcr.yml at master\n"));
    }

    /// Every template carries the same first line as the renderers that write
    /// one themselves; if it moves, they all have to move with it.
    #[test]
    fn every_generated_compose_file_opens_with_the_same_line() {
        for template in [
            &*BASE_TEMPLATE,
            &*OVERLAY_TEMPLATE,
            &*OCS_TEMPLATE,
            &*S3_TEMPLATE,
        ] {
            assert_eq!(template.lines().next(), Some(GENERATED_HEADER));
        }
        for rendered in [
            render_chaps_overlay(8000, None),
            render_umbrella(&[], None),
            render_umbrella(&["compose.a.yml".to_string()], Some("demo-1ab2c3")),
        ] {
            assert_eq!(rendered.lines().next(), Some(GENERATED_HEADER));
        }
    }

    #[test]
    fn umbrella_with_no_models_is_an_empty_service_map() {
        let text = render_umbrella(&[], None);
        let doc = parse(&text);
        assert!(doc.get("include").is_none(), "an empty include is rejected");
        assert_eq!(
            doc["services"],
            Value::Mapping(serde_yaml_ng::Mapping::new())
        );
    }

    #[test]
    fn umbrella_includes_one_line_per_overlay() {
        let one = render_umbrella(&["compose.chapkit-ewars-model.yml".to_string()], None);
        let doc = parse(&one);
        assert_eq!(
            doc["include"],
            Value::Sequence(vec!["compose.chapkit-ewars-model.yml".into()])
        );
        assert!(doc.get("services").is_none());

        let files: Vec<String> = ["a", "b", "c"]
            .iter()
            .map(|n| format!("compose.{n}.yml"))
            .collect();
        let three = render_umbrella(&files, None);
        let doc = parse(&three);
        assert_eq!(
            doc["include"],
            Value::Sequence(files.iter().map(|f| f.as_str().into()).collect())
        );
    }

    #[test]
    fn the_umbrella_names_the_compose_project_too() {
        // It is the one file always in the `-f` list: a deployment with
        // chap-core turned off has no compose.chaps.yml to carry the name.
        for files in [vec![], vec!["compose.chapkit-ewars-model.yml".to_string()]] {
            let text = render_umbrella(&files, Some("mychap-1ab2c3"));
            assert_eq!(
                parse(&text)["name"].as_str(),
                Some("mychap-1ab2c3"),
                "{text}"
            );
        }
        assert!(!render_umbrella(&[], None).contains("name:"));
    }

    fn ocs_spec() -> OcsSpec {
        OcsSpec {
            host_port: crate::components::OCS_DEFAULT_PORT,
            image_tag: crate::components::OCS_DEFAULT_TAG.to_string(),
            s3: false,
        }
    }

    fn s3_spec() -> S3Spec {
        S3Spec {
            host_port: None,
            image_tag: crate::components::S3_DEFAULT_TAG.to_string(),
        }
    }

    #[test]
    fn ocs_publishes_its_port_and_mounts_the_scaffolded_config() {
        let text = render_ocs(&ocs_spec());
        assert_no_tokens(&text);
        assert_eq!(text.lines().next(), Some(GENERATED_HEADER));
        assert_eq!(
            text.lines().nth(1),
            Some("# ocs: Open Climate Service (https://github.com/dhis2/open-climate-service)")
        );

        let doc = parse(&text);
        let svc = service(&doc, "ocs");
        assert_eq!(
            svc["image"].as_str(),
            Some("ghcr.io/dhis2/open-climate-service:${OCS_IMAGE_TAG:-main}")
        );
        // Multi-arch upstream, so no platform pin and no `depends_on` on chap.
        assert!(svc.get("platform").is_none());
        assert!(svc.get("depends_on").is_none());
        assert!(svc.get("networks").is_none());
        // The image ships its own HEALTHCHECK; a second one here would only
        // be a copy to keep in step.
        assert!(svc.get("healthcheck").is_none());
        assert_eq!(svc["restart"].as_str(), Some("unless-stopped"));
        assert_eq!(svc["init"].as_bool(), Some(true));
        assert_eq!(
            svc["ports"],
            Value::Sequence(vec![Value::String("9000:9000".into())])
        );
        // Quoted: an unquoted number is not a string, which is what compose
        // wants of an environment value.
        assert_eq!(svc["environment"]["PORT"].as_str(), Some("9000"));
        assert_eq!(
            svc["environment"]["CLIMATE_SERVICE_CONFIG"].as_str(),
            Some("/app/climate-service.yaml")
        );
        assert!(svc["environment"].get("ROOT_PATH").is_none());
        assert_eq!(
            svc["volumes"][0].as_str(),
            Some("./ocs/climate-service.yaml:/app/climate-service.yaml:ro")
        );
        assert_eq!(svc["volumes"][1]["source"].as_str(), Some(OCS_VOLUME));
        assert_eq!(svc["volumes"][1]["target"].as_str(), Some("/app/data"));
        assert!(doc["volumes"].get(OCS_VOLUME).is_some());
        // One service: OCS needs no init container of its own.
        assert_eq!(doc["services"].as_mapping().unwrap().len(), 1);
    }

    #[test]
    fn ocs_gets_the_s3_variables_only_when_the_store_is_enabled() {
        let without = render_ocs(&ocs_spec());
        assert!(!without.contains("S3_ENDPOINT"));
        // Dropping the block must not leave a blank line behind.
        assert!(!without.contains("\n\n    volumes:"));

        let with = render_ocs(&OcsSpec {
            s3: true,
            ..ocs_spec()
        });
        assert_no_tokens(&with);
        assert!(
            with.contains("# Forward-looking: OCS does not read these yet."),
            "{with}"
        );
        let env = &parse(&with)["services"]["ocs"]["environment"];
        assert_eq!(env["S3_ENDPOINT"].as_str(), Some("http://s3:9000"));
        assert_eq!(env["S3_ACCESS_KEY"].as_str(), Some("${S3_ACCESS_KEY:-}"));
        assert_eq!(env["S3_SECRET_KEY"].as_str(), Some("${S3_SECRET_KEY:-}"));
        assert_eq!(env["S3_BUCKET"].as_str(), Some("ocs"));
    }

    #[test]
    fn a_custom_ocs_port_moves_only_the_host_side() {
        let text = render_ocs(&OcsSpec {
            host_port: 9010,
            ..ocs_spec()
        });
        assert_eq!(
            parse(&text)["services"]["ocs"]["ports"],
            Value::Sequence(vec![Value::String("9010:9000".into())])
        );
        // The container port is what chap-core reaches, and it never moves.
        assert_eq!(
            parse(&text)["services"]["ocs"]["environment"]["PORT"].as_str(),
            Some("9000")
        );
    }

    #[test]
    fn the_store_is_internal_until_a_port_is_asked_for() {
        let internal = render_s3(&s3_spec());
        assert_no_tokens(&internal);
        let doc = parse(&internal);
        let svc = service(&doc, "s3");
        assert_eq!(
            svc["expose"],
            Value::Sequence(vec![Value::String("9000".into())])
        );
        assert!(svc.get("ports").is_none(), "nothing is published");

        let published = render_s3(&S3Spec {
            host_port: Some(9002),
            ..s3_spec()
        });
        assert_no_tokens(&published);
        let svc = &parse(&published)["services"]["s3"];
        assert_eq!(
            svc["ports"],
            Value::Sequence(vec![Value::String("9002:9000".into())])
        );
        assert_eq!(
            svc["expose"],
            Value::Sequence(vec![Value::String("9000".into())])
        );
    }

    #[test]
    fn the_store_carries_its_credentials_its_health_check_and_a_bucket_init() {
        let text = render_s3(&s3_spec());
        assert_eq!(text.lines().next(), Some(GENERATED_HEADER));
        assert_eq!(
            text.lines().nth(1),
            Some("# s3: RustFS, an S3-compatible object store (https://github.com/rustfs/rustfs)")
        );
        let doc = parse(&text);
        let svc = service(&doc, "s3");
        assert_eq!(
            svc["image"].as_str(),
            Some("rustfs/rustfs:${S3_IMAGE_TAG:-latest}")
        );
        assert!(svc.get("platform").is_none(), "multi-arch upstream");
        assert_eq!(svc["restart"].as_str(), Some("unless-stopped"));
        assert_eq!(svc["init"].as_bool(), Some(true));
        // The image's own variable names, substituted from .env.
        let env = &svc["environment"];
        assert_eq!(
            env["RUSTFS_ACCESS_KEY"].as_str(),
            Some("${S3_ACCESS_KEY:-}")
        );
        assert_eq!(
            env["RUSTFS_SECRET_KEY"].as_str(),
            Some("${S3_SECRET_KEY:-}")
        );
        assert_eq!(env["RUSTFS_VOLUMES"].as_str(), Some("/data"));
        assert_eq!(
            svc["healthcheck"]["test"][1].as_str(),
            Some("curl"),
            "the image ships curl, which is what signs the bucket request too"
        );
        assert_eq!(svc["volumes"][0]["source"].as_str(), Some(S3_VOLUME));
        assert!(doc["volumes"].get(S3_VOLUME).is_some());

        // The one-shot creates the bucket with the same image, so nothing else
        // has to be pulled; `$$` survives for the container's own shell.
        let init = service(&doc, "s3-init");
        assert_eq!(init["restart"].as_str(), Some("no"));
        assert_eq!(
            init["depends_on"]["s3"]["condition"].as_str(),
            Some("service_healthy")
        );
        let command = init["command"][0].as_str().unwrap();
        assert!(
            command.contains("--aws-sigv4 \"aws:amz:us-east-1:s3\""),
            "{command}"
        );
        assert!(
            command.contains("-X PUT \"http://s3:9000/ocs\""),
            "{command}"
        );
        assert!(
            text.contains("$${S3_ACCESS_KEY}"),
            "a literal $ for compose"
        );
        assert_eq!(doc["services"].as_mapping().unwrap().len(), 2);
    }

    #[test]
    fn the_ocs_config_scaffold_says_when_it_is_the_example() {
        let example = render_ocs_config(&OcsConfigSpec::default());
        assert_no_tokens(&example);
        assert!(example.contains(OCS_EXAMPLE_MARKER), "{example}");
        let doc = parse(&example);
        assert_eq!(doc["id"].as_str(), Some("sierra-leone-climate-service"));
        assert_eq!(doc["name"].as_str(), Some("Sierra Leone Climate Service"));
        assert_eq!(doc["extent"]["name"].as_str(), Some("Sierra Leone"));
        assert_eq!(doc["extent"]["country_code"].as_str(), Some("SLE"));
        assert_eq!(doc["extent"]["bbox"][0].as_f64(), Some(-13.5));
        assert_eq!(doc["extent"]["bbox"][3].as_f64(), Some(10.0));
        assert_eq!(doc["data_dir"].as_str(), Some("/app/data"));
    }

    #[test]
    fn the_ocs_config_scaffold_fills_the_values_it_is_given() {
        let spec = crate::compose::spec::OcsConfigRequest {
            name: Some("Malawi".into()),
            country_code: Some("mwi".into()),
            bbox: Some("32.6,-17.2,35.9,-9.3".into()),
        }
        .into_spec();
        let text = render_ocs_config(&spec);
        assert_no_tokens(&text);
        assert!(
            !text.contains(OCS_EXAMPLE_MARKER),
            "these are the operator's values"
        );
        let doc = parse(&text);
        assert_eq!(doc["id"].as_str(), Some("malawi-climate-service"));
        assert_eq!(doc["name"].as_str(), Some("Malawi Climate Service"));
        assert_eq!(doc["extent"]["name"].as_str(), Some("Malawi"));
        assert_eq!(doc["extent"]["country_code"].as_str(), Some("MWI"));
        assert_eq!(doc["extent"]["bbox"][1].as_f64(), Some(-17.2));
        assert_eq!(doc["data_dir"].as_str(), Some("/app/data"));
    }

    fn env_spec() -> EnvSpec {
        EnvSpec {
            postgres_user: "chap".into(),
            postgres_password: "0123456789abcdef0123456789abcdef".into(),
            postgres_db: "chap_core".into(),
            chap_image_tag: None,
            api_port: crate::project::DEFAULT_API_PORT,
            api_token: None,
            registration_key: None,
            model_tag_pins: Vec::new(),
        }
    }

    #[test]
    fn env_writes_the_postgres_credentials() {
        let text = render_env(&env_spec());
        assert_no_tokens(&text);
        // Its own first line: `.env` is written once, not rendered from
        // `.chaps/` like the compose files.
        assert_eq!(
            text.lines().next(),
            Some(
                "# Written once by chaps init; chaps never rewrites it. \
                 See the docs for each setting."
            )
        );
        assert!(text.contains("\nPOSTGRES_USER=chap\n"));
        assert!(text.contains("\nPOSTGRES_PASSWORD=0123456789abcdef0123456789abcdef\n"));
        assert!(text.contains("\nPOSTGRES_DB=chap_core\n"));
        assert!(text.contains("\n# CHAP_API_TOKEN=\n"));
        assert!(text.contains("\n# SERVICEKIT_REGISTRATION_KEY=\n"));
        assert!(text.contains("\n# CHAP_DATABASE_URL=\n"));
        assert!(text.ends_with('\n'));
    }

    #[test]
    fn env_carries_an_active_api_port_line_at_every_port() {
        // Active even at the default: the one port the stack publishes has to
        // be discoverable where an operator would change it.
        let text = render_env(&env_spec());
        assert!(text.contains("\nCHAP_API_PORT=8000\n"), "{text}");
        assert!(!text.contains("# CHAP_API_PORT"));

        let text = render_env(&EnvSpec {
            api_port: 8123,
            ..env_spec()
        });
        assert!(text.contains("\nCHAP_API_PORT=8123\n"));
    }

    #[test]
    fn env_activates_the_chap_tag_only_when_it_is_pinned() {
        for tag in [None, Some("latest".to_string())] {
            let text = render_env(&EnvSpec {
                chap_image_tag: tag.clone(),
                ..env_spec()
            });
            assert!(text.contains("\n# CHAP_IMAGE_TAG=latest\n"), "{tag:?}");
        }
        let text = render_env(&EnvSpec {
            chap_image_tag: Some("v1.2.3".into()),
            ..env_spec()
        });
        assert!(text.contains("\nCHAP_IMAGE_TAG=v1.2.3\n"));
        assert!(!text.contains("# CHAP_IMAGE_TAG"));
    }

    #[test]
    fn env_lists_one_commented_pin_per_model() {
        let text = render_env(&EnvSpec {
            model_tag_pins: vec![
                (tag_env_var("chapkit_ewars_model"), "sha-fa880a1".into()),
                (tag_env_var("auto_arima_chapkit"), "sha-70c07a9".into()),
            ],
            ..env_spec()
        });
        assert!(text.contains("\n# CHAPKIT_EWARS_MODEL_IMAGE_TAG=sha-fa880a1\n"));
        assert!(text.contains("\n# AUTO_ARIMA_CHAPKIT_IMAGE_TAG=sha-70c07a9\n"));
        assert!(!text.contains("none yet"));

        // Without models the section keeps a body rather than a blank line.
        let empty = render_env(&env_spec());
        assert!(empty.contains(NO_TAG_PINS));
        assert!(!empty.ends_with("\n\n"));
    }

    #[test]
    fn env_leaves_both_secrets_commented_without_authentication() {
        let text = render_env(&env_spec());
        assert!(text.contains("\n# CHAP_API_TOKEN=\n"), "{text}");
        assert!(
            text.contains("\n# SERVICEKIT_REGISTRATION_KEY=\n"),
            "{text}"
        );
        assert_eq!(
            crate::auth::state_of(&text),
            crate::project::AuthState::default()
        );
    }

    #[test]
    fn env_writes_both_secrets_as_active_lines_when_authentication_is_on() {
        let token = "a".repeat(64);
        let key = "b".repeat(64);
        let text = render_env(&EnvSpec {
            api_token: Some(token.clone()),
            registration_key: Some(key.clone()),
            ..env_spec()
        });
        assert_no_tokens(&text);
        assert!(
            text.contains(&format!("\nCHAP_API_TOKEN={token}\n")),
            "{text}"
        );
        assert!(
            text.contains(&format!("\nSERVICEKIT_REGISTRATION_KEY={key}\n")),
            "{text}"
        );
        // No placeholder left behind for either one.
        assert!(!text.contains("# CHAP_API_TOKEN="));
        assert!(!text.contains("# SERVICEKIT_REGISTRATION_KEY="));
        // And the rendered file reads back as "both on".
        assert_eq!(
            crate::auth::state_of(&text),
            crate::project::AuthState {
                api_token: true,
                registration_key: true
            }
        );
    }

    #[test]
    fn a_secret_line_is_an_assignment_or_a_placeholder() {
        assert_eq!(
            secret_line("CHAP_API_TOKEN", Some("abc")),
            "CHAP_API_TOKEN=abc"
        );
        assert_eq!(secret_line("CHAP_API_TOKEN", None), "# CHAP_API_TOKEN=");
    }
}
