//! Filling the compose text templates.
//!
//! The templates are plain text with `@KEY@` tokens rather than a template
//! engine, because compose's own `${VAR:-default}` syntax collides with the
//! usual `{{ }}` delimiters and a serde round trip would drop the comments.

mod dhis2;
mod ocs;
mod overlay;

pub use dhis2::{
    DHIS2_CONTAINER_PORT, DHIS2_DB_VOLUME, DHIS2_DEFAULT_SEED_URL, DHIS2_DUMP_VOLUME,
    DHIS2_HOME_VOLUME, render_dhis2, render_dhis2_config, seed_value,
};
pub use ocs::{
    OCS_EXAMPLE_MARKER, OCS_VOLUME, S3_VOLUME, render_ocs, render_ocs_config, render_s3,
};
pub use overlay::render_overlay;

#[cfg(test)]
pub(crate) use dhis2::{DHIS2_DB_IMAGE, DHIS2_DUMP_IMAGE, DHIS2_SEED_MOUNT};

use crate::auth::{API_TOKEN_ENV_VAR, REGISTRATION_KEY_ENV_VAR};
use crate::compose::spec::{BaseSpec, EnvSpec};
use crate::project::API_PORT_ENV_VAR;
use std::sync::LazyLock;

/// Rewrite CRLF line endings as LF.
///
/// Every file rendered here is compared byte for byte: by `chaps sync`
/// against what is on disk, and by the tests against the golden fixture. The
/// templates are compiled in with `include_str!`, so on a Windows checkout
/// with git's default `core.autocrlf` they would arrive with CRLF and the
/// rendered file would differ from the same file rendered anywhere else.
/// Passing them through here once makes the output `\n` on every platform,
/// whatever the checkout did.
pub(crate) fn normalize_newlines(text: &str) -> String {
    text.replace("\r\n", "\n")
}

/// chap-core's `compose.ghcr.yml`, verbatim but for the header comment.
static BASE_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/compose.base.yml")));

/// The first line of every compose file `chaps sync` renders, templates
/// included.
///
/// It says what the file is and where to change it, and nothing else: the
/// explanations live in the docs, so an upgrade of this CLI never rewrites a
/// paragraph in someone's deployment.
pub(crate) const GENERATED_HEADER: &str =
    "# Generated by chaps from .chaps/; edit there and run `chaps sync`.";
/// The generated `.env`.
static ENV_TEMPLATE: LazyLock<String> =
    LazyLock::new(|| normalize_newlines(include_str!("templates/env.example")));

/// Placeholder for the pin section of a `.env` with no models enabled, so the
/// section never renders as a dangling heading above a blank line.
pub(crate) const NO_TAG_PINS: &str = "# (none yet; `chaps models enable` adds one line per model)";

/// Render the base `compose.yml`.
///
/// With `spec.upstream` the body is chap-core's own `compose.ghcr.yml` at that
/// tag, byte for byte but for its line endings, behind the shared header line
/// plus one naming the tag; without it the copy compiled into the binary is
/// used as it is. Both renderings are a pure function of the project state,
/// which is what lets `chaps sync` treat `compose.yml` as an artifact.
pub fn render_base(spec: &BaseSpec) -> String {
    let Some(upstream) = &spec.upstream else {
        return BASE_TEMPLATE.clone();
    };
    let mut out = format!(
        "{GENERATED_HEADER}\n# chap-core compose.ghcr.yml at {}\n",
        upstream.tag
    );
    out.push_str(&normalize_newlines(&upstream.body));
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// Render `compose.chaps.yml`: the chaps-owned settings that sit on top of
/// the fetched `compose.yml`.
///
/// It exists because the base file is upstream's, byte for byte, and because
/// `include:` cannot override a service the main file defines - only a
/// separate `-f` entry can. The `!override` tag (Compose 2.24.4+, which is why
/// that is this CLI's supported minimum) replaces chap's own `ports:` list
/// rather than adding to it, which is what keeps the API on exactly one host
/// port.
///
/// `api_port` is rendered as the `${CHAP_API_PORT:-...}` default, so the file
/// stands on its own while `.env` stays the way to change the port without
/// touching `.chaps/`.
///
/// `project_name` is the top-level `name:`, which is what keeps this
/// deployment's containers and volumes to itself; see [`project_name_block`].
///
/// The `environment:` block hands chap-core the registration key. Upstream's
/// `compose.ghcr.yml` passes only `CHAP_API_TOKEN` into the service, so a
/// deployment with authentication on has a chap-core that knows the API token
/// and not the key - and then rejects every model's `X-Service-Key` with a
/// 401. Compose merges `environment` maps across `-f` files additively, so
/// this adds the one variable without touching upstream's file. It is
/// rendered whether or not the deployment has a key: with none in `.env` the
/// variable arrives empty, which is what chap-core reads as "not set".
///
/// The same block sets `XDG_RUNTIME_DIR`. chap-core runs gunicorn 26, which
/// opens a control socket at `$XDG_RUNTIME_DIR/gunicorn.ctl` and falls back to
/// `$HOME/.gunicorn/` - a path the service's read-only root filesystem
/// refuses, so every start logs `Control server error: [Errno 30] Read-only
/// file system: '/home/chap'`. The server comes up either way; pointing the
/// socket at the writable `/tmp` tmpfs keeps that line out of the log. Only
/// the `chap` service needs it: the worker runs celery, not gunicorn.
///
/// `checkout` is a chap-core checkout the chap and worker images are built
/// from instead of pulled (`chaps init --source`). `pull_policy: build` makes
/// every `chaps up` build the checkout as it is now, which Docker's layer
/// cache keeps cheap when nothing changed, and makes `compose pull` skip them.
pub fn render_chaps_overlay(
    api_port: u16,
    project_name: Option<&str>,
    checkout: Option<&str>,
) -> String {
    let (chap_image, worker_image) = checkout_images(project_name);
    let (chap_build, worker_build) = match checkout {
        Some(path) => (
            format!(
                "\x20   image: {chap_image}\n\
                 \x20   build:\n\
                 \x20     context: {path}\n\
                 \x20   pull_policy: build\n"
            ),
            format!(
                "\x20 worker:\n\
                 \x20   image: {worker_image}\n\
                 \x20   build:\n\
                 \x20     context: {path}\n\
                 \x20     dockerfile: Dockerfile.worker\n\
                 \x20   pull_policy: build\n"
            ),
        ),
        None => (String::new(), String::new()),
    };
    format!(
        "{GENERATED_HEADER}\n\
         {}\
         services:\n\
         \x20 chap:\n\
         {chap_build}\
         \x20   ports: !override\n\
         \x20     - \"${{{API_PORT_ENV_VAR}:-{api_port}}}:8000\"\n\
         \x20   environment:\n\
         \x20     {REGISTRATION_KEY_ENV_VAR}: ${{{REGISTRATION_KEY_ENV_VAR}:-}}\n\
         \x20     # Keeps gunicorn's control socket off the read-only root; drop it once chap-core disables that socket.\n\
         \x20     XDG_RUNTIME_DIR: /tmp\n\
         {worker_build}",
        project_name_block(project_name)
    )
}

/// The image a chap-core checkout's API is built into, for a deployment
/// compose can make no project name out of.
pub const CHECKOUT_CHAP_IMAGE: &str = "chap-core-checkout:local";
/// The same for the worker.
pub const CHECKOUT_WORKER_IMAGE: &str = "chap-worker-checkout:local";

/// The images a chap-core checkout is built into: named after the compose
/// project, so two deployments built from two checkouts (two worktrees, say)
/// never overwrite each other's build.
pub fn checkout_images(project_name: Option<&str>) -> (String, String) {
    match project_name {
        Some(name) => (
            format!("{name}-chap:checkout"),
            format!("{name}-worker:checkout"),
        ),
        None => (
            CHECKOUT_CHAP_IMAGE.to_string(),
            CHECKOUT_WORKER_IMAGE.to_string(),
        ),
    }
}

/// The top-level `name:` key.
///
/// Without it compose names the project after the directory, so two
/// deployments in directories of the same name share every container name and
/// every named volume - a fresh `chaps up` then inherits the database of a
/// deployment it has never heard of. Compose takes the `name:` of the last
/// `-f` file that sets one, so every chaps-owned file carries the same value
/// and any subset of the `-f` list names the same project.
///
/// Empty for a deployment whose directory name compose can make no project
/// name out of at all; compose falls back to its own rule there, as it always
/// has.
pub(crate) fn project_name_block(project_name: Option<&str>) -> String {
    match project_name {
        Some(name) => format!("name: {name}\n"),
        None => String::new(),
    }
}

/// Render the generated `.env`.
pub fn render_env(spec: &EnvSpec) -> String {
    // An active line only when the tag says something `latest` does not.
    let chap_image_tag_line = match spec.chap_image_tag.as_deref() {
        Some(tag) if tag != "latest" => format!("CHAP_IMAGE_TAG={tag}"),
        _ => "# CHAP_IMAGE_TAG=latest".to_string(),
    };
    let pins = if spec.model_tag_pins.is_empty() {
        NO_TAG_PINS.to_string()
    } else {
        spec.model_tag_pins
            .iter()
            .map(|(var, tag)| format!("# {var}={tag}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    fill(
        &ENV_TEMPLATE,
        &[
            ("POSTGRES_USER", &spec.postgres_user),
            ("POSTGRES_PASSWORD", &spec.postgres_password),
            ("POSTGRES_DB", &spec.postgres_db),
            ("CHAP_IMAGE_TAG_LINE", &chap_image_tag_line),
            ("API_PORT", &spec.api_port.to_string()),
            (
                "CHAP_API_TOKEN_LINE",
                &secret_line(API_TOKEN_ENV_VAR, spec.api_token.as_deref()),
            ),
            (
                "REGISTRATION_KEY_LINE",
                &secret_line(REGISTRATION_KEY_ENV_VAR, spec.registration_key.as_deref()),
            ),
            ("MODEL_TAG_PINS", &pins),
        ],
    )
}

/// One secret's `.env` line: an active assignment when there is a value, and
/// otherwise the commented placeholder.
///
/// The placeholder is written even when the deployment has no authentication,
/// so the variable is discoverable where an operator would look for it, and so
/// `chaps auth enable` has a line to uncomment in place rather than appending
/// one at the bottom of the file.
fn secret_line(var: &str, value: Option<&str>) -> String {
    match value {
        Some(value) => format!("{var}={}", crate::dotenv::encode(value)),
        None => format!("# {var}="),
    }
}

/// Render `compose.marketplace.yml` from the ordered overlay file names.
///
/// With no overlays this must emit `services: {}` rather than an empty
/// `include:` list, which compose rejects.
///
/// It carries the project `name:` as well, and it is the one file that is
/// always in the `-f` list: a deployment with `chap-core` turned off has no
/// `compose.chaps.yml` to carry it.
pub fn render_umbrella(files: &[String], project_name: Option<&str>) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str(&project_name_block(project_name));
    if files.is_empty() {
        out.push_str("services: {}\n");
        return out;
    }
    out.push_str("include:\n");
    for file in files {
        out.push_str(&format!("  - {file}\n"));
    }
    out
}

/// Replace every `@KEY@` token in `template` with its value.
pub(crate) fn fill(template: &str, vars: &[(&str, &str)]) -> String {
    let mut out = template.to_string();
    for (key, value) in vars {
        out = out.replace(&format!("@{key}@"), value);
    }
    out
}

#[cfg(test)]
mod tests;
