//! The vendored marketplace snapshot, compiled into the binary.
//!
//! Used as the last-resort fallback when the registry can be neither fetched
//! nor read from cache, so `chaps` works on a machine that has never had
//! network access.
//!
//! Refresh the files under `vendor/marketplace/` with
//! `scripts/vendor-marketplace.sh` and commit the result. There is nothing to
//! update here: [`build.rs`](../../build.rs) reads `registry.yaml` and
//! generates the `(path, contents)` table below, so a model added or dropped
//! upstream is picked up by the next build.

// `FILES`: the `(relative path, file contents)` pairs, generated by the build
// script. The first entry is always `registry.yaml`; the rest are the model
// files keyed by the same relative paths the index lists, in index order. A
// doc comment cannot sit on a macro invocation, so this one is a plain one.
include!(concat!(env!("OUT_DIR"), "/embedded_files.rs"));

/// The embedded snapshot: `registry.yaml` first, then the model files.
#[cfg(test)]
pub fn files() -> &'static [(&'static str, &'static str)] {
    FILES
}

/// The embedded `registry.yaml`.
pub fn index_yaml() -> &'static str {
    FILES[0].1
}

/// The embedded model files, without the index.
pub fn model_files() -> Vec<(String, String)> {
    FILES[1..]
        .iter()
        .map(|(name, body)| ((*name).to_string(), (*body).to_string()))
        .collect()
}

#[cfg(test)]
mod tests;
